In [4]:
import pandas as pd
import numpy as np
print(pd)

<module 'pandas' from 'c:\\Users\\keval\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pandas\\__init__.py'>

In [19]:
data = np.array([[1, 2, 3], [2, 5, 6]])
var = pd.DataFrame(data)
# print(var)
# print(pd.Series(data[0], index= ['a', 'b', 'c']))
print(pd.Series(data[0], index= ['a', 'b', 'c'])['b'])

2

In [223]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, np.nan]
}

df = pd.DataFrame(data)

# print(df.loc[0:2])
df.index
len(df)
len(df.index)

# rows, columns = df.shape
# print(f"{rows} {columns}")
df.count()
# len(df.columns)
# df.size
df.ndim
df.memory_usage()
df.loc[1]
df.iloc[1]

data_ins = pd.DataFrame([[400, 79]], columns=df.columns)
df = pd.concat([df, data_ins], ignore_index=True)
df = df.drop(labels=3)
df

   calories  duration
0       420      50.0
1       380      40.0
2       390       NaN

In [96]:
df.insert(loc=2, column="XYZ", value=np.array([0,0,0]))

In [98]:
# del df['XYZ']
df.pop('XYZ')

0    0
1    0
2    0
Name: XYZ, dtype: int64

In [105]:
a = df['calories'].head(2) + df['duration'].head(2)
np.sum(a)

np.float64(890.0)

In [122]:
# sorting

df.sort_values(by=['calories', 'duration'], ascending=False, inplace=True)

In [125]:
df.sort_index()

   calories  duration
0       420      50.0
1       380      40.0
2       390       NaN

In [129]:
# filtering
# filtered_data = df['calories'] < 400
filtered_data = (df['calories'] >= 400) | (df['duration'] >= 80)
df[filtered_data]

   calories  duration
0       420      50.0

In [158]:
df['calories'].where(cond=~pd.isna(df['duration']), other=np.nan)

0    420.0
1    380.0
2      NaN
Name: calories, dtype: float64

In [161]:
for col_label, col in df.items():
    print(col_label, col, sep='\n', end='\n\n')

calories
0    420
1    380
2    390
Name: calories, dtype: int64

duration
0    50.0
1    40.0
2     NaN
Name: duration, dtype: float64

In [178]:
for index, rows in df.iterrows():
    print(f"{index} {rows['duration']}")

0 50.0
1 40.0
2 nan

In [184]:
dt = pd.date_range(start='2019-10-27 00:00:00.0', periods=24, freq='D')
dt

DatetimeIndex(['2019-10-27', '2019-10-28', '2019-10-29', '2019-10-30',
               '2019-10-31', '2019-11-01', '2019-11-02', '2019-11-03',
               '2019-11-04', '2019-11-05', '2019-11-06', '2019-11-07',
               '2019-11-08', '2019-11-09', '2019-11-10', '2019-11-11',
               '2019-11-12', '2019-11-13', '2019-11-14', '2019-11-15',
               '2019-11-16', '2019-11-17', '2019-11-18', '2019-11-19'],
              dtype='datetime64[us]', freq='D')

In [198]:
# df['calories'].is_unique
# df = df.set_index()
df.dtypes

calories      int64
duration    float64
dtype: object

In [221]:
df1 = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

format_func = lambda x: '%.2f' % x

df_formatted_map = df1.map(format_func)
print(df_formatted_map)

            b      d      e
Utah    -1.74   1.20  -1.06
Ohio     1.96   0.81  -0.11
Texas   -0.12   0.27  -1.09
Oregon  -0.01  -0.96   1.21

In [243]:
data = {'Key': ['A', 'B', 'C', 'A', 'B', 'C'],
        'Data1': [0, 1, 2, 3, 4, 5],
        'Data2': [5, 0, 3, 3, 7, 9]}
df = pd.DataFrame(data)

# grouped_data = df.groupby('Key').sum()
# print(grouped_data)
# group_means = df.groupby('Key')['Data1'].mean()
# print(group_means)
df.groupby('Key')['Data1'].transform(lambda x: x.fillna(x.mean()))
df.groupby('Key').filter(lambda x: x['Data1'].mean() > 1.5)

agg_functions = {'Data1': ['sum', 'mean'], 'Data2': ['min', 'max']}
multi_agg = df.groupby('Key').agg(agg_functions)
print(multi_agg)

    Data1      Data2
      sum mean   min max
Key
A       3  1.5     3   5
B       5  2.5     0   7
C       7  3.5     3   9

In [ ]:
df_1 = pd.DataFrame({'key': ['A', 'B', 'C', 'D'], 'value1': [1, 2, 3, 4]})
df_2 = pd.DataFrame({'key': ['B', 'D', 'E', 'F'], 'value2': [5, 6, 7, 8]})

# Inner merge (default)
merged_df = pd.merge(df_1, df_2, on='key', how='inner')
print(merged_df)

  key  value1  value2
0   A       1     NaN
1   B       2     5.0
2   C       3     NaN
3   D       4     6.0

In [250]:
# join

df10 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                    'B': ['B0', 'B1', 'B2']},
                   index=['K0', 'K1', 'K2'])

df20 = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                   index=['K0', 'K2', 'K3'])

# Perform a left join (default behavior)
result = df10.join(df20)
print(result)

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [268]:
# csv
from io import StringIO

csv_obj = pd.read_csv('user.csv')
df = pd.DataFrame(csv_obj)
print(df)

data = "a,b,c,d\n1,2,3,4\n5,6,7,8\n9,10,11"
df_101 = pd.read_csv(StringIO(data))
print(df_101)

   id    name            dob
0   1    ajay   '2004-07-06'
1   2   ajay2   '2004-03-07'
2   3   ajay3   '2003-02-08'
   a   b   c    d
0  1   2   3  4.0
1  5   6   7  8.0
2  9  10  11  NaN

In [2]:
!pip install pandas openpyxl

Requirement already satisfied: pandas in C:\Users\keval\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.1)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\keval\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\keval\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\keval\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.3)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: six>=1.5 in C:\Users\keval\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [19]:
import pandas as pd
df = pd.read_excel('pandas_practical.xlsx')
df

   Roll no  english  maths  science
0        1       19     13       17
1        2       14     20       18
2        3       15     18       19
3        4       13     14       14
4        5       19     16       20

In [13]:
df.at[4, 'english'] = 19
print(df.at[4, 'english'])

19

In [18]:
with pd.ExcelWriter('pandas_practical.xlsx', mode='a', engine='openpyxl', if_sheet_exists='replace') as writer:
    df.to_excel(writer, sheet_name='Sheet1', index=False)