In [1]:
import pandas as pd
import numpy as np

In [50]:
speeds = pd.DataFrame(
    [
        ("bird", "Falconiformes", 389.0),
        ("bird", "Psittaciformes", 24.0),
        ("mammal", "Carnivora", 58),
        ("mammal", "Primates", np.nan),
        ("mammal", "Carnivora", 80.2),
    ],
    index=["falcon", "parrot", "lion", "monkey", "leopard"],
    columns=("class", "order", "max_speed"),
)

speeds
grp_by_obj = speeds.groupby("class", sort=False)
grp_by_obj.max_speed.sum()
grp_by_obj.sum()
speeds.groupby("class", sort=False, dropna=False).get_group('mammal')
grp_by_obj.groups
len(grp_by_obj)

2

In [72]:
# GroupBy with MultiIndex
data = {
    'Category': ['A', 'A', 'B', 'B', 'C', 'C'],
    'SubCategory': ['X', 'Y', 'X', 'Y', 'X', 'Y'],
    'Values': [10, 20, 30, 40, 50, 60]
}
df = pd.DataFrame(data).set_index(['Category', 'SubCategory'])

print("Original DataFrame:")
print(df)

# Group by the first level ('Category') and sum the 'Values'
grouped_data = df.groupby(level=['Category'])['Values'].sum()
# grouped_data = df.groupby([pd.Grouper(level=0), "SubCategory"])['Values'].sum()

print(grouped_data)

Original DataFrame:
                      Values
Category SubCategory
A        X                10
         Y                20
B        X                30
         Y                40
C        X                50
         Y                60
Category
A     30
B     70
C    110
Name: Values, dtype: int64

In [124]:
for x, y in df.groupby('SubCategory'):
    print(x)
    print(y)

df.groupby('Category', sort=False).describe()
df.groupby('Category', sort=False).agg(lambda x : set(x))
df.groupby('Category', sort=False).agg(min_value = pd.NamedAgg(column='Values', aggfunc="min"))

X
                      Values
Category SubCategory
A        X                10
B        X                30
C        X                50
Y
                      Values
Category SubCategory
A        Y                20
B        Y                40
C        Y                60

          min_value
Category
A                10
B                30
C                50

In [153]:
grouped = speeds.groupby("class")["max_speed"]
print(speeds)
print("\n")
# print(grouped.rank())
# print(grouped.transform("sum"))
print(grouped.transform(lambda x : x+1))

          class           order  max_speed
falcon     bird   Falconiformes      389.0
parrot     bird  Psittaciformes       24.0
lion     mammal       Carnivora       58.0
monkey   mammal        Primates        NaN
leopard  mammal       Carnivora       80.2


falcon     390.0
parrot      25.0
lion        59.0
monkey       NaN
leopard     81.2
Name: max_speed, dtype: float64

In [183]:
df_re = pd.DataFrame({"A": [1] * 10 + [5] * 10, "B": np.arange(20)})
# print(df_re)
# print(df_re.groupby('A').rolling(2).B.mean())
# df_re.groupby("A").expanding().sum()

df_re.groupby('A').head(4)
df_re.groupby('A').tail(4)
df_re.groupby('A').nth(4)
df_re.groupby('A').apply(lambda x : x.describe())

                B
A
1 count  10.00000
  mean    4.50000
  std     3.02765
  min     0.00000
  25%     2.25000
  50%     4.50000
  75%     6.75000
  max     9.00000
5 count  10.00000
  mean   14.50000
  std     3.02765
  min    10.00000
  25%    12.25000
  50%    14.50000
  75%    16.75000
  max    19.00000